### ISSUE TITLE
Typo Feast

### ISSUE THREAD

**Issue by avedetvedea** [team31415/edgedb#1]
The title and the first paragraph...

EdgeDB facing the Hacker News guantlet...
The Hacker News community has an extraoridnary way of picking apart anything that is laid bare on the news feed. So how did EdgeDB's two major milestones, this year, fare amongst the Hacker News crowd?

How many typos and wrong use of language can you find here?

**Comment by team31415** [comment]
Thanks for the feedback.  

BTW- Enjoyed your "Typo Feast" title it was a creative way of expressing the truth.
